---

- hosts: localhost
  vars:
    nios_provider:
      host: 10.36.118.2
      username: cloudadmin
      password: infoblox
      wapi_version: 2.1

  connection: local
  tasks:
   - name: create zone
     nios_zone:
       name: ansibletestzone.com
       view: ansibleDnsView
       extattrs:
         Site: Test Site
       comment: Created with Ansible
       state: present
       provider: "{{ nios_provider }}"
