---
  
- hosts: localhost
  vars:
    nios_provider:
      host: 10.36.118.2
      username: cloudadmin
      password: infoblox

  connection: local
  tasks:
   - name: Create Nios CNAME record
     nios_cname_record:
       name: cname.ansible.com
       canonical: realhost.ansible.com
       comment: Created with Ansible
       state: absent
       provider: "{{ nios_provider }}"
